"""“TableInit”

Revision ID: 3ba0be5d8587
Revises: 7146aa86ec62
Create Date: 2023-03-15 17:20:51.638653

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ba0be5d8587'
down_revision = '7146aa86ec62'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
