"""“TableInit”

Revision ID: 7146aa86ec62
Revises: 3c8b0dacfc85
Create Date: 2023-03-15 17:11:48.931184

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7146aa86ec62'
down_revision = '3c8b0dacfc85'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('game_sales',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Name', sa.String(), nullable=True),
    sa.Column('Platform', sa.String(), nullable=True),
    sa.Column('Year', sa.Integer(), nullable=True),
    sa.Column('Genre', sa.String(), nullable=True),
    sa.Column('Publisher', sa.String(), nullable=True),
    sa.Column('NA_Sales', sa.Float(), nullable=True),
    sa.Column('EU_Sales', sa.Float(), nullable=True),
    sa.Column('JP_Sales', sa.Float(), nullable=True),
    sa.Column('Other_Sales', sa.Float(), nullable=True),
    sa.Column('Global_Sales', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('Name')
    )
    op.create_index(op.f('ix_game_sales_id'), 'game_sales', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_game_sales_id'), table_name='game_sales')
    op.drop_table('game_sales')
    # ### end Alembic commands ###
