"""“TableFix”

Revision ID: 718afea34b38
Revises: 80d0e3925763
Create Date: 2023-03-15 17:26:29.121509

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '718afea34b38'
down_revision = '80d0e3925763'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('game_sales_Name_key', 'game_sales', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('game_sales_Name_key', 'game_sales', ['Name'])
    # ### end Alembic commands ###
